before_install:
  - gem install bundler 
language: ruby
script: 'bundle exec rake ci --trace'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  #- jruby-18mode blacklisted for crash on travis http://travis-ci.org/#!/mbj/session/jobs/1846734
  #- jruby-19mode blacklisted for crash on travis http://travis-ci.org/#!/mbj/session/jobs/1896117
  - rbx-18mode
  - rbx-19mode
notifications:
  email:
    - mbj@seonic.net
