before_install:
  - gem install bundler 
language: ruby
script: 'bundle exec rake ci'
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode 
  - jruby-head
  - rbx-18mode
  - rbx-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: 1.8.7 # Rcov false positive
    - rvm: ree # Rcov false positive 
notifications:
  email:
    - mbj@seonic.net
